[build]
  cmd = "cd /app && go build -o tmp/server github.com/labasubagia/temporal-poc/cmd/server"
  bin = "tmp/server"
  exclude_dir = ["vendor", ".git", "cmd/worker", "cmd/ws", "tmp", "bin"]

[run]
  env_pass = ["TEMPORAL_HOST_URL", "TEMPORAL_NAMESPACE", "PORT", "WS_PORT", "WS_HOST"]

[log]
  main_only = false