[build]
  cmd = "go build -o tmp/ws github.com/labasubagia/temporal-poc/cmd/ws"
  bin = "tmp/ws"
  exclude_dir = ["vendor", ".git", "cmd/server", "cmd/worker", "tmp", "bin"]

[run]
  env_pass = ["WS_PORT", "WS_HOST"]

[log]
  main_only = false