FROM golang:1.26-alpine

WORKDIR /app

RUN go install github.com/cosmtrek/air@v1.52.0

COPY go.mod go.sum ./
RUN go mod download

COPY air-server.toml air-worker.toml air-ws.toml ./

EXPOSE 8080 8081

CMD ["air", "-c", "air-server.toml"]